import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

// Register PWA service worker (generated by vite-plugin-pwa)
// The virtual:pwa-register module is only available when vite-plugin-pwa is configured
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  import('virtual:pwa-register')
    .then(({ registerSW }) => {
      registerSW({
        onNeedRefresh() {
          window.location.reload();
        },
        onOfflineReady() {
          console.log('✅ App ready to work offline');
        },
      });
    })
    .catch(() => {});
}

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);